ci: remove `web` service_healthy dependents with service_started ones
Why:
`web` hangs in "Waiting" state, then fails the command with:
> ERROR: dependency failed to start: container sentry-self-hosted-web-1 is unhealthy

`nginx` and `relay` containers appears to be inactive/stopped.

Most likely caused by host system not meeting the requirements to run well.
Consider this as a temporary fix.